spring:
  application:
    name: auction
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: mysql
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
#      use-new-id-generator-mappings: false
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #    properties:
#      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
#    platform:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    url: "jdbc:mysql:///youngwon_db"
    username: youngwon
    password: 123
#    hikari:
#      minimum-idle: 1
#      maximum-pool-size: 5
#      pool-name: H2_DB
  data:
    web:
      pageable:
        default-page-size: 10
      sort:
        sort-parameter: id
jwt:
  token:
    header: Authorization
    issuer: youngwonseo
    client-secret: 223232jrhjkhbsjs
    expiry-seconds: 0
server:
  port: 8080



  #spring.rabbitmq.host=localhost
  #spring.rabbitmq.port=5672
  #spring.rabbitmq.username=guest
  #spring.rabbitmq.password=guest

#  spring.data.web.pageable.default-page-size=10
#  spring.data.web.sort.sort-parameter=id


#spring.datasource.url=jdbc:mysql://34.121.152.35:3307/youngwon_db
#spring.datasource.username=youngwon
#spring.datasource.password=youngwon!!!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto=update
#
#
##spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
##spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
##spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
#
#spring.jpa.properties.hibernate.default_batch_fetch_size=1000
##spring.jpa.properties.hibernate.show_sql=true
##spring.jpa.properties.hibernate.format_sql=true
##logging.level.org.hibernate.type.descriptor.sql=trace
#
#jwt.token.header=Authorization
#jwt.token.issuer=youngwonseo
#jwt.token.client-secret=223232jrhjkhbsjs
#jwt.token.expiry-seconds=0
#
#
##spring.rabbitmq.host=localhost
##spring.rabbitmq.port=5672
##spring.rabbitmq.username=guest
##spring.rabbitmq.password=guest
#
#spring.data.web.pageable.default-page-size=10
#spring.data.web.sort.sort-parameter=id